# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name scratch.andykee.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name scratch.andykee.com;

    ssl_certificate     /etc/letsencrypt/live/scratch.andykee.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/scratch.andykee.com/privkey.pem;

    location /api/ {
        proxy_pass         http://api:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location / {
        root       /usr/share/nginx/html;
        try_files  $uri $uri/ /index.html;
    }
}
